# Write your code here :-)
print("Hello world!")
print("What is your name?")
myName = input()  # idk why this is only called input and i hate it
print("It is nice to meet you " + myName)
print("The length of your name is: ")
print(len(myName))
print("What is your age?")
myAge = input()
print("You will be " + str(int(myAge) + 1) + " in a year")
